### ISSUE TITLE
Support for `jakarta.inject` API

### ISSUE THREAD

**Issue by stariy95** [bootique/bootique-di#37]
Since Bootique 3.0 introduces support for Jakarta APIs in various modules we may think about adding support for `jakarta.inject` to the Bootique DI

**Comment by andrus** [comment]
+1. And let's also try to do some research beyond jakarta.inject. I think we are still mostly ignorning JAXB and maybe a few more libs that are not used directly, but are imported by the integrated frameworks.

**Comment by andrus** [comment]
Closing, moved to https://github.com/bootique/bootique/issues/349
